# Generated by Django 3.0.5 on 2020-04-24 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attraction', '0003_remove_touristattraction_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='news', width_field='width_field')),
                ('height_field', models.IntegerField(default=100)),
                ('width_field', models.IntegerField(default=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('touristattraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attraction.TouristAttraction')),
            ],
        ),
    ]
