# Generated by Django 3.0.5 on 2020-04-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantouristattraction',
            old_name='touristattractions',
            new_name='touristattraction',
        ),
    ]
