# Generated by Django 3.0.5 on 2020-04-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20200422_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
