# Generated by Django 3.0.5 on 2020-05-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
