# Generated by Django 3.0.5 on 2020-04-22 02:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True)),
                ('lat', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=9)),
            ],
        ),
    ]
