# Generated by Django 3.0.5 on 2020-04-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
