# Generated by Django 3.0.5 on 2020-04-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0005_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='province',
        ),
    ]
