# Generated by Django 3.0.5 on 2020-05-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='touristattraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attraction.TouristAttraction'),
        ),
    ]
