# Generated by Django 3.0.5 on 2020-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0008_rating_touristattraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
