# Generated by Django 3.0.5 on 2020-05-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0012_auto_20200514_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
